CREATE OR REPLACE FUNCTION add_vote(
  p_user_id INT,
  p_thread_id INT,
  p_vote_value INT)

RETURNS TABLE(vote_id INT,
              user_id INT,
              thread_id INT,
              vote_value INT)
AS
$BODY$
  BEGIN
    RETURN QUERY
        INSERT INTO vote (user_id, thread_id, vote_value)
        VALUES (p_user_id, p_thread_id, p_vote_value)
        RETURNING vote.vote_id, vote.user_id, vote.thread_id, vote.vote_value;
  END;
$BODY$
LANGUAGE plpgsql VOLATILE;