CREATE OR REPLACE FUNCTION get_users_by_nickname_or_email(p_nickname CITEXT, p_email CITEXT)
  RETURNS TABLE(user_id INT,
                nickname CITEXT,
                email CITEXT,
                about TEXT,
                fullname TEXT)
AS
$BODY$
  BEGIN
    RETURN QUERY SELECT u.user_id, u.nickname, u.email, u.about, u.fullname
    FROM users u
    WHERE u.nickname = p_nickname or u.email = p_email;
  END;
$BODY$
LANGUAGE plpgsql VOLATILE;