@startuml

posts: post_id [INT]
posts: thread_id [INT]
posts: forum_id [INT]
posts: user_id [INT]
posts: parent_id [INT]
posts: message [TEXT]
posts: created [DATETIME]
posts: is_edited [BOOLEAN]
posts ---> forumsg
posts ---> users : author
posts ---> threads
posts -> posts: parent

vote: vote_id [INT]
vote: user_id [INT]
vote: thread_id [INT]
vote: vote_value [INT]
vote ---> users
vote ---> threads

users: user_id [INT]
users: nickname [CITEXT]
users: email [CITEXT]
users: about [TEXT]
users: fullname [TEXT]

forums: forum_id [INT]
forums: slug [CITEXT]
forums: user_id [INT]
forums: title [text]
forums -> users: responsible

threads: thread_id [INT]
threads: slug [CITEXT]
threads: forum_id [INT]
threads: user_id [INT]
threads: created [DATETIME]
threads: message [TEXT]
threads: title [TEXT]
threads -> forums
threads --> users : author

@enduml
