@startuml

post: post_id [INT]
post: author_id [INT]
post: forum_id [INT]
post: thread_id [INT]
post: parent_id [INT]
post: created [TIME]
post: message [TEXT]
post: isEdited [BOOLEAN]
post ---> userTable : author
post ---> forum
post ---> thread
post ---> post: parent

vote: vote_id [INT]
vote: author_id [INT]
vote: thread_id [INT]
vote: voice [INT]
vote -> userTable
vote -> thread

userTable: user_id [INT]
userTable: about [TEXT]
userTable: email [CITEXT]
userTable: fullname [TEXT]
userTable: nickname [CITEXT]

forum: forum_id [INT]
forum: responsible_user_id [INT]
forum: slug [CITEXT]
forum: title [text]
forum -> userTable: responsible

thread: thread_id [INT]
thread: author_id [INT]
thread: forum_id [INT]
thread: created [TEXT]
thread: message [TEXT]
thread: slug [CITEXT]
thread: title [TEXT]
thread: votes [INT]

thread ---> forum
thread ---> userTable: author

@enduml

