version: "3"
services:

  postgres:
    restart: always
    image: postgres:9.5
    networks:
      - backend
    ports:
      - "5454:5432"

  loader:
    build:
      context: ../database/loader/

    volumes:
      - ../database:/tmp/database

    env_file: .env

    networks:
      - backend

    depends_on:
      - postgres

#  api:
#    build:
#      context: ../src/api
#    networks:
#      - backend
#    ports:
#      - "5000:80"
#    volumes:
#      - ../src/api/tech_forum_api:/tmp/api/tech_forum_api
#    env_file: .env
#    environment:
#      - CACHE_TYPE=simple
#      - PYTHONPATH=/tmp/api/
#    command: bash -c "cd /tmp/api/tech_forum_api && /usr/local/bin/gunicorn -w 1 -b :80 app:app"


networks:
  backend:
